services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: api-build
      args:
        VITE_APP_TITLE: ${VITE_APP_TITLE:-LabsChat}
    ports:
      - ${PORT:-3080}:${PORT:-3080}
    restart: always
    depends_on:
      - mongodb
      - rag_api
      - meilisearch
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      # Server Configuration
      - HOST=${HOST:-localhost}
      - PORT=${PORT:-3080}
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      # Domain Configuration
      - DOMAIN_CLIENT=${DOMAIN_CLIENT}
      - DOMAIN_SERVER=${DOMAIN_SERVER}
      - NO_INDEX=true
      - TRUST_PROXY=${TRUST_PROXY:-1}
      # Logging
      - CONSOLE_JSON=${CONSOLE_JSON:-false}
      - DEBUG_LOGGING=${DEBUG_LOGGING:-true}
      - DEBUG_CONSOLE=${DEBUG_CONSOLE:-false}
      # Endpoints
      - ENDPOINTS=${ENDPOINTS:-google,openAI,agents,anthropic}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - DIGITALOCEAN_API_KEY=${DIGITALOCEAN_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODELS=${ANTHROPIC_MODELS:-claude-haiku-4-5}
      - GOOGLE_KEY=${GOOGLE_KEY}
      - GOOGLE_MODELS=${GOOGLE_MODELS:-gemini-2.5-flash-lite,gemini-2.5-flash,gemini-2.5-pro}
      - GOOGLE_SERVICE_KEY_FILE=${GOOGLE_SERVICE_KEY_FILE}
      - GOOGLE_LOC=${GOOGLE_LOC:-global}
      - MISTRAL_OCR_LOC=${MISTRAL_OCR_LOC:-us-central1}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODELS=${OPENAI_MODELS:-gpt-5-nano,gpt-5-mini,gpt-5,gpt-5.4-nano,gpt-5.4-mini,gpt-5.4}
      - DEBUG_OPENAI=${DEBUG_OPENAI:-false}
      # Search
      - MEILI_HOST=http://meilisearch:7700
      - SEARCH=true
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      # Moderation
      - OPENAI_MODERATION=${OPENAI_MODERATION:-false}
      - OPENAI_MODERATION_API_KEY=${OPENAI_API_KEY}
      - BAN_VIOLATIONS=${BAN_VIOLATIONS:-true}
      # Authentication & Registration
      - ALLOW_EMAIL_LOGIN=${ALLOW_EMAIL_LOGIN:-true}
      - ALLOW_SOCIAL_LOGIN=${ALLOW_SOCIAL_LOGIN:-false}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-false}
      - ALLOW_PASSWORD_RESET=${ALLOW_PASSWORD_RESET:-true}
      - ALLOW_UNVERIFIED_EMAIL_LOGIN=${ALLOW_UNVERIFIED_EMAIL_LOGIN:-true}
      # Security & Sessions
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      # Email Configuration
      - EMAIL_HOST=${EMAIL_HOST:-smtp.resend.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_ENCRYPTION=${EMAIL_ENCRYPTION:-starttls}
      - EMAIL_USERNAME=${EMAIL_USERNAME:-resend}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME:-LabsChat.Ai}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@updates.capybaralabs.com.br}
      - EMAIL_SUPPORT=${EMAIL_SUPPORT:-}
      # RAG Configuration
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      # UI
      - APP_TITLE=${APP_TITLE:-LabsChat.Ai}
      - CUSTOM_FOOTER=${CUSTOM_FOOTER:-LabsChat.Ai}
      - HELP_AND_FAQ_URL=${HELP_AND_FAQ_URL:-https://docs.labschat.ai}
      - SHOW_BIRTHDAY_ICON=false
      # Extras
      - CHECK_BALANCE=${CHECK_BALANCE:-false}
      - START_BALANCE=${START_BALANCE:-10000000}
      - NODE_ENV=production
    volumes:
      - ../files/images:/app/client/public/images
      - ../files/uploads:/app/uploads
      - ../files/logs:/app/api/logs
      - ../files/librechat.yaml:/app/librechat.yaml
      - ../files/customization:/app/client/dist/assets/customization

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    command: mongod --noauth

  meilisearch:
    image: getmeili/meilisearch:v1.12.3
    restart: always
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - meili_data:/meili_data

  vectordb:
    image: pgvector/pgvector:0.8.0-pg15-trixie
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-mydatabase}
      - POSTGRES_USER=${POSTGRES_USER:-myuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mypassword}
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
      - POSTGRES_DB=${POSTGRES_DB:-mydatabase}
      - POSTGRES_USER=${POSTGRES_USER:-myuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mypassword}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_OPENAI_API_KEY=${RAG_OPENAI_API_KEY}
      - GOOGLE_KEY=${GOOGLE_KEY}
      - RAG_GOOGLE_API_KEY=${RAG_GOOGLE_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER:-openai}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL:-text-embedding-3-small}
    restart: always
    depends_on:
      - vectordb

volumes:
  pgdata2:
  mongo_data:
  meili_data:
